version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mapeia a porta do contêiner para a porta do host
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/workshop-mongo # Conexão com MongoDB no contêiner

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017" # Porta padrão do MongoDB
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
